AllCops:
  NewCops: enable

Naming/FileName:
  Exclude:
    - 'lib/rails-mcp.rb'

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 100

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockNesting:
  Max: 4