#!/usr/bin/env ruby
# frozen_string_literal: true

$stdout.sync = true
require 'bundler/setup'
require 'rails-mcp'

original_stdout = $stdout.dup

begin
  $stdout.reopen($stderr)

  if File.exist?('config/environment.rb')
    require './config/environment'
  else
    warn 'Aviso: Não estou na raiz de um projeto Rails.'
  end
rescue StandardError => e
  warn "Erro fatal: #{e.message}"
  exit 1
ensure
  $stdout.reopen(original_stdout)
end

Rails::Mcp::Server.new.start
