#!/usr/bin/env ruby

require "bundler/setup"
require "rails-mcp" 

if File.exist?("config/environment.rb")
  warn "🛤️  Detectei um projeto Rails! Carregando ambiente..."
  
  require "./config/environment"
  
  warn "Rails carregado com sucesso!"
else
  warn "Aviso: Não estou na raiz de um projeto Rails."
end

Rails::Mcp::Server.new.start